In [3]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# order引数を指定しない場合はデフォルトで2ノルムが計算される
# 行方向のノルム計算
row_norm = np.linalg.norm(matrix, axis=1)
print("行方向のノルム:", row_norm)

# 列方向のノルム計算
col_norm = np.linalg.norm(matrix, axis=0)
print("列方向のノルム:", col_norm)

行方向のノルム: [ 3.74165739  8.77496439 13.92838828]
列方向のノルム: [ 8.1240384   9.64365076 11.22497216]


In [23]:
matrix = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
matrix1 = matrix.reshape(2, -1)  # -1を指定すると自動で要素数を計算してくれる
matrix2 = matrix.reshape(-1, 2)
matrix3 = matrix.reshape(-1, 2, order="F")  # order引数でFortranスタイルの順序で要素を並べることができる
vector3 = matrix3.reshape(-1, order="F")  # 1次元配列に変換
vector3_ = matrix3.reshape(-1)
print(matrix1)
print(matrix2)
print(matrix3)
print(vector3)
print(vector3_)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  6  2  7  3  8  4  9  5 10]


In [19]:
matrix = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
matrix = matrix.reshape(-1, 2, order="F")
print(matrix)
norm = np.linalg.norm(matrix, axis=1)
print(norm)
tile = np.tile(norm[:, np.newaxis], (1, 2))
print(tile)
t = np.maximum(tile, 0) * matrix
print(t)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
[ 6.08276253  7.28010989  8.54400375  9.8488578  11.18033989]
[[ 6.08276253  6.08276253]
 [ 7.28010989  7.28010989]
 [ 8.54400375  8.54400375]
 [ 9.8488578   9.8488578 ]
 [11.18033989 11.18033989]]
[[  6.08276253  36.49657518]
 [ 14.56021978  50.96076922]
 [ 25.63201124  68.35202996]
 [ 39.39543121  88.63972022]
 [ 55.90169944 111.80339887]]


In [24]:
vec = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(vec[0:5])

[1 2 3 4 5]
